### ISSUE TITLE
Style content edit on dashboard

### ISSUE THREAD

**Issue by gregwiechec** [advanced-cms/content-grid#26]
![image](https://user-images.githubusercontent.com/12434079/71243574-ef551180-2310-11ea-8c5b-186a63e77049.png)

**Comment by barteksekula** [comment]
center it on the screen
add scroll if needed
check if validation works
check local file upload

**Comment by barteksekula** [comment]
~~center it on the screen~~
~~add scroll if needed~~
check if validation works
check local file upload

**Comment by barteksekula** [comment]
~~center it on the screen~~
~~add scroll if needed~~
~~fix validation~~
~~check if local file upload is possible, check how it works on mobile~~
